import type { FeedGroup } from '../app/types/feed'
// 友链检测 CLI 需要使用显式导入和相对路径
import { myFeed } from '../blog.config'
// eslint-disable-next-line unused-imports/no-unused-imports
import { getFavicon, getGithubAvatar, getGithubIcon, getOciqGroupAvatar, getOicqAvatar, OicqAvatarSize } from './utils/img'

export default [
	// #region Clarity
	{
		name: '清晰体验',
		desc: '使用 Clarity 博客主题构建的网站。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			myFeed,
		],
	},
	// #endregion
	// #region 网上邻居
	{
		name: '网上邻居',
		desc: '哔——啵——电波通讯中，欢迎常来串门。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '是Yangs',
				desc: '一个前端Bug构造师的博客',
				link: 'https://www.isyangs.cn/',
				feed: 'https://www.isyangs.cn/feed.xml',
				icon: 'https://www.isyangs.cn/favicon.svg',
				avatar: 'https://7.isyangs.cn/8/655c9835780a0-8.jpg',
				archs: ['Vue', '国内 CDN'],
				date: '2024-01-29',
				comment: '高中时认识的小学校友，目前从事前端开发。',
			},
			{
				// title: '他说',
				// imgurl: 'https://090909.top/assets/images/logo.ico',
				desc: '梁栋烨的博客网站。',
				// siteurl: 'https://090909.top',
				// tags: ['Blog'],
				// weight: 5,
				// enabled: true,
				author: '他说',
				icon: 'https://090909.top/assets/images/logo.ico',
				avatar: 'https://090909.top/assets/images/logo.ico',
				link: 'https://090909.top',
				date: '2026-06-23',
			},
			{
				// title: "Hyper001's Blog",
				// imgurl: 'https://blog.hyper001.cn/images/avatar.jpeg',
				desc: '记录学习，分享生活，保持热爱，奔赴山海。',
				// siteurl: 'https://blog.hyper001.cn',
				// tags: ['Blog'],
				// weight: 5,
				// enabled: true,
				author: "Hyper001's Blog",
				icon: 'https://blog.hyper001.cn/images/avatar.jpeg',
				avatar: 'https://blog.hyper001.cn/images/avatar.jpeg',
				link: 'https://blog.hyper001.cn',
				date: '2026-06-23',
			},
			{
				// title: '小枫_QWQ的Blog',
				// imgurl: 'https://q.qlogo.cn/headimg_dl?dst_uin=1432777209&spec=640&img_type=jpg',
				desc: '欢迎来到小枫_QWQ的Blog！这是一个致力于分享前后端技术的博客。同时也分享一些闲聊碎语',
				// siteurl: 'https://blog.xiaofengqwq.com',
				// tags: ['Blog'],
				// weight: 5,
				// enabled: true,
				author: '小枫_QWQ的Blog',
				icon: 'https://q.qlogo.cn/headimg_dl?dst_uin=1432777209&spec=640&img_type=jpg',
				avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=1432777209&spec=640&img_type=jpg',
				link: 'https://blog.xiaofengqwq.com',
				date: '2026-06-23',
			},
			{
				// title: 'TT清沫uk',
				// imgurl: 'https://ts1.tc.mm.bing.net/th/id/OIP-C.6WsD9caLSNQFhJOi77soRAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
				desc: 'TT清沫ukの博客',
				// siteurl: 'https://ttquk.netlify.app',
				// tags: ['Blog'],
				// weight: 5,
				// enabled: true,
				author: 'TT清沫uk',
				icon: 'https://ts1.tc.mm.bing.net/th/id/OIP-C.6WsD9caLSNQFhJOi77soRAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
				avatar: 'https://ts1.tc.mm.bing.net/th/id/OIP-C.6WsD9caLSNQFhJOi77soRAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
				link: 'https://ttquk.netlify.app',
				date: '2026-06-23',
			},
			{
				// title: '高新炀的小站',
				// imgurl: 'https://xinyang-gao.github.io/assets/avatar.webp',
				desc: '一个装着些稀奇古怪东西的个人小站，欢迎来逛逛~',
				// siteurl: 'https://xinyang-gao.github.io',
				// tags: ['Blog'],
				// weight: 5,
				// enabled: true,
				author: '高新炀的小站',
				icon: 'https://xinyang-gao.github.io/assets/avatar.webp',
				avatar: 'https://xinyang-gao.github.io/assets/avatar.webp',
				link: 'https://xinyang-gao.github.io',
				date: '2026-06-23',
			},
			{
				// title: '番茄主理人',
				// imgurl: 'https://q1.qlogo.cn/g?b=qq&nk=20447289&s=640',
				desc: '坐而言不如起而行.',
				// siteurl: 'https://fqzlr.com/',
				// tags: ['Blog'],
				// weight: 5,
				// enabled: true,
				author: '番茄主理人',
				icon: 'https://q1.qlogo.cn/g?b=qq&nk=20447289&s=640',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=20447289&s=640',
				link: 'https://fqzlr.com/',
				date: '2026-06-23',
			},
			{
				// title: 'MmzMing的知识库',
				// imgurl: 'https://i.stardots.io/784774835/StarDots-2026052116374135506.jpg',
				desc: '哈基米，南北绿豆',
				// siteurl: 'https://tblog.mmzhiku.xyz',
				// tags: ['Blog'],
				// weight: 5,
				// enabled: true,
				author: 'MmzMing的知识库',
				icon: 'https://i.stardots.io/784774835/StarDots-2026052116374135506.jpg',
				avatar: 'https://i.stardots.io/784774835/StarDots-2026052116374135506.jpg',
				link: 'https://tblog.mmzhiku.xyz',
				date: '2026-06-23',
			},
			{
				// title: 'Hyde Blog',
				// imgurl: 'https://seasir.top/assets/avatar.avif',
				desc: '人心中的成见是一座大山',
				// siteurl: 'https://seasir.top/',
				// tags: ['Blog'],
				// weight: 5,
				// enabled: true,
				author: 'Hyde Blog',
				icon: 'https://seasir.top/assets/avatar.avif',
				avatar: 'https://seasir.top/assets/avatar.avif',
				link: 'https://seasir.top/',
				date: '2026-06-23',
			},
			{
				// title: '涵哲子居',
				// imgurl: 'https://afipo.top/logo.webp',
				desc: '天哲地理，共公卿好',
				// siteurl: 'https://afipo.top/',
				// tags: ['Blog'],
				// weight: 5,
				// enabled: true,
				// source: 'https://github.com/olinll/Firefly-Blog/issues/11',
				// qq: '3860169579',
				author: '涵哲子居',
				icon: 'https://afipo.top/logo.webp',
				avatar: 'https://afipo.top/logo.webp',
				link: 'https://afipo.top/',
				date: '2026-06-23',
			},
			{
				// title: 'MineDensity',
				// imgurl: 'https://www.minedensity.top/favicon.svg',
				desc: '这个网站是我送给互联网的一本手绘笔记。如果你在这里找到了什么让你停留的东西，那我们就已经是朋友了。',
				// siteurl: 'https://www.minedensity.top/',
				// tags: ['Blog'],
				// weight: 5,
				// enabled: true,
				// source: 'https://github.com/olinll/Firefly-Blog/issues/9',
				// qq: '2560868231',
				author: 'MineDensity',
				icon: 'https://www.minedensity.top/favicon.svg',
				avatar: 'https://www.minedensity.top/favicon.svg',
				link: 'https://www.minedensity.top/',
				date: '2026-06-23',
			},
		],
	},
	// #endregion
] satisfies FeedGroup[]
