import type { FeedGroup } from '../app/types/feed'
// 友链检测 CLI 需要使用显式导入和相对路径
import { myFeed } from '../blog.config'
// eslint-disable-next-line unused-imports/no-unused-imports
import { getFavicon, getGithubAvatar, getGithubIcon, getOciqGroupAvatar, getOicqAvatar, OicqAvatarSize } from './utils/img'

export default [
	// #region 本站
	{
		name: '关于本站',
		desc: '记录学习、实践与思考的个人博客。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			myFeed,
			{
				author: '顾拾柒 & Hako',
				title: '17 & Hako',
				desc: 'a little corner for the two of us.',
				link: 'https://hako.love/',
				icon: 'https://hako.love/icon.svg?icon.3c8wdhom-ig9p.svg',
				avatar: 'https://hako.love/icon.svg?icon.3c8wdhom-ig9p.svg',
				archs: ['Next.js'],
				date: '2026-06-10',
			},
			{
				author: 'Olinl Note',
				title: 'Olinl Note',
				desc: '笔记仓库。',
				link: 'https://doc.olinl.com/',
				icon: 'https://doc.olinl.com/olinl.png',
				avatar: 'https://doc.olinl.com/olinl.png',
				archs: ['VuePress'],
				date: '2026-06-10',
			},
			{
				author: '顾拾柒',
				title: 'Olinl 笔记',
				desc: '记录个人笔记与碎片想法。',
				link: 'https://note.olinl.com/',
				icon: 'https://note.olinl.com/logo.webp',
				avatar: 'https://note.olinl.com/logo.webp',
				date: '2026-06-10',
			},
		],
	},
	// #endregion
	// #region 相谈甚多
	{
		name: '相谈甚多',
		desc: '与朋友们交流心得，分享生活的博客。',
		entries: [
			{
				author: 'Endless Poetry',
				title: '万物流转',
				desc: '传播我的虚弱',
				link: 'https://www.flows.xin/',
				// feed: 'https://lijie.cool/rss.xml',
				icon: 'https://www.flows.xin/_next/image?url=%2Favatar%2Favatar.webp&w=96&q=75',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=407450353&s=640',
				archs: ['React', 'Cloudflare'],
				date: '2026-09-01',
				comment: '我哥！'
			},
			{
				author: 'Replow Lv.999',
				title: 'SilverCode_Nexus',
				desc: 'Replow的小站',
				link: 'https://www.replow.org/',
				// feed: 'https://www.replow.org/atom.xml',
				icon: 'https://cdn.replow.org/replow-org/images/tx.ico',
				avatar: 'https://cdn.replow.org/replow-org/images/tx.ico',
				archs: ['PHP', 'Cloudflare'],
				date: '2026-08-09',
			},
			{
				author: 'Tixxin',
				title: 'Tixxin的博客',
				desc: 'Tixxin的个人博客',
				link: 'https://tix.xin/',
				icon: 'https://tix.xin/favicon.ico',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=1019692929&s=640',
				archs: ['Nuxt'],
				date: '2026-06-20',
				comment: '仍处于演示状态。。。未完待续'
			},
			{
				author: 'MmzMing',
				title: 'MmzMing的知识库',
				desc: '哈基米，南北绿豆',
				link: 'https://tblog.mmzhiku.xyz',
				feed: 'https://tblog.mmzhiku.xyz/atom.xml',
				icon: 'https://i.stardots.io/784774835/StarDots-2026052116374135506.jpg',
				avatar: 'https://i.stardots.io/784774835/StarDots-2026052116374135506.jpg',
				archs: ['Astro', 'EdgeOne'],
				date: '2026-06-20',
			},
			{
				author: '番茄主理人',
				title: '番茄主理人',
				desc: '坐而言不如起而行.',
				link: 'https://blog.fqzlr.com/',
				feed: 'https://blog.fqzlr.com/rss.xml',
				icon: 'https://q1.qlogo.cn/g?b=qq&nk=20447289&s=640',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=20447289&s=640',
				archs: ['Astro', 'EdgeOne'],
				date: '2026-06-20',
			},
			{
				author: '7',
				title: 'lijie blog',
				desc: '懒于当下，勤于长远',
				link: 'https://lijie.cool/',
				feed: 'https://lijie.cool/rss.xml',
				icon: 'https://lijie.cool/image/avatar.jpg',
				avatar: 'https://lijie.cool/image/avatar.jpg',
				archs: ['Cloudflare'],
				date: '2026-09-01',
			},

		],
	},
	// #endregion
	// #region 网上邻居 since 2024
	{
		name: '网上邻居',
		desc: '哔——啵——电波通讯中，欢迎常来串门。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '梁栋烨',
				title: '他说',
				desc: '梁栋烨的博客网站。',
				link: 'https://090909.top/',
				feed: 'https://090909.top/atom.xml',
				icon: 'https://090909.top/assets/images/logo.ico',
				avatar: 'https://090909.top/assets/images/logo.ico',
				archs: ['Hexo', 'Cloudflare'],
				date: '2026-06-20',
			},
			{
				author: 'Hyper001',
				title: 'Hyper001’s Blog',
				desc: '记录学习，分享生活，保持热爱，奔赴山海。',
				link: 'https://blog.hyper001.site/',
				// feed: 'https://blog.hyper001.site/atom.xml',
				icon: 'https://blog.hyper001.site/images/avatar.jpeg',
				avatar: 'https://blog.hyper001.site/images/avatar.jpeg',
				archs: ['Valaxy', 'Cloudflare'],
				date: '2026-06-20',
			},
			{
				author: '小枫_QWQ',
				title: '小枫_QWQ的Blog',
				desc: '欢迎来到小枫_QWQ的Blog！这是一个致力于分享前后端技术的博客。同时也分享一些闲聊碎语',
				link: 'https://blog.xiaofengqwq.com/',
				feed: 'https://blog.xiaofengqwq.com/rss.xml',
				icon: 'https://q.qlogo.cn/headimg_dl?dst_uin=1432777209&spec=640&img_type=jpg',
				avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=1432777209&spec=640&img_type=jpg',
				archs: ['Typecho', 'Cloudflare'],
				date: '2026-06-20',
			},
			{
				author: 'TT清沫uk',
				title: 'TT清沫uk',
				desc: 'TT清沫ukの博客',
				link: 'https://ttquk.github.io/',
				feed: 'https://ttquk.github.io/atom.xml',
				icon: 'https://ts1.tc.mm.bing.net/th/id/OIP-C.6WsD9caLSNQFhJOi77soRAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
				avatar: 'https://ts1.tc.mm.bing.net/th/id/OIP-C.6WsD9caLSNQFhJOi77soRAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
				archs: ['Hexo', 'GitHub Pages'],
				date: '2026-06-20',
			},
			{
				author: '高新炀',
				title: '高新炀的小站',
				desc: '一个装着些稀奇古怪东西的个人小站，欢迎来逛逛~',
				link: 'https://gxy.cn.mt/',
				feed: 'https://gxy.cn.mt/rss.xml',
				icon: 'https://gxy.cn.mt/assets/avatar.webp',
				avatar: 'https://gxy.cn.mt/assets/avatar.webp',
				archs: ['Python', 'GitHub Pages'],
				date: '2026-06-20',
			},

			{
				author: 'Hyde',
				title: 'Hyde Blog',
				desc: '人心中的成见是一座大山',
				link: 'https://seasir.top/',
				feed: 'https://seasir.top/rss.xml',
				icon: 'https://seasir.top/assets/avatar.avif',
				avatar: 'https://seasir.top/assets/avatar.avif',
				archs: ['Astro', 'EdgeOne'],
				date: '2026-06-21',
			},
			{
				author: 'MineDensity',
				title: 'MineDensity',
				desc: '这个网站是我送给互联网的一本手绘笔记。如果你在这里找到了什么让你停留的东西，那我们就已经是朋友了。',
				link: 'https://www.minedensity.top/',
				feed: 'https://www.minedensity.top/rss.xml',
				icon: 'https://www.minedensity.top/favicon.svg',
				avatar: 'https://www.minedensity.top/favicon.svg',
				archs: ['Vue', '服务器'],
				date: '2026-06-21',
			},

			{
				author: 'gc',
				title: 'gc的小站',
				desc: '综合性网站，希望能对你有帮助',
				link: 'https://gcweb.cc/',
				// feed: 'https://gcweb.cc/atom.xml',
				icon: 'https://www.gcweb.cc/static/img/pig.jpg',
				avatar: 'https://www.gcweb.cc/static/img/pig.jpg',
				archs: ['HTML', '服务器'],
				date: '2026-06-25',
			},
			{
				author: '陶然',
				title: '陶然',
				desc: '一团温暖的粘土博客',
				link: 'https://taoran.weppp.cyou/',
				feed: 'https://taoran.weppp.cyou/rss.xml',
				icon: 'https://taoran.weppp.cyou/favicon.svg',
				avatar: 'https://taoran.weppp.cyou/favicon.svg',
				archs: ['Astro', '服务器'],
				date: '2026-06-26',
			},
			{
				author: '涵哲子居',
				title: '涵哲子居',
				desc: '天哲地理，共公卿好',
				link: 'https://iluc.cn/',
				feed: 'https://iluc.cn/rss.xml',
				icon: 'https://iluc.cn/logo.webp',
				avatar: 'https://iluc.cn/logo.webp',
				archs: ['Astro', 'Cloudflare'],
				date: '2026-06-28',
			},
			{
				author: 'miuo',
				title: 'miuo’s blog',
				desc: '记录文章、笔记、实验和暂时不想丢掉的内容。',
				link: 'https://miuo.me/',
				feed: 'https://miuo.me/rss.xml',
				icon: 'https://miuo.me/avatar.avif',
				avatar: 'https://miuo.me/avatar.avif',
				archs: ['Astro', 'Vercel'],
				date: '2026-06-30',
			},
			{
				author: '十三',
				title: '十三',
				desc: '欲买桂花同载酒，终不似，少年游。',
				link: 'https://blog.nw177.cn/',
				feed: 'https://blog.nw177.cn/rss.xml',
				icon: 'https://blog.nw177.cn/assets/avatar.webp',
				avatar: 'https://blog.nw177.cn/assets/avatar.webp',
				archs: ['Astro'],
				date: '2026-07-06',
			},
			{
				author: 'SUPERSTAR',
				title: '灵光一刻|SUPERSTAR',
				desc: '只为了记录每个时刻的想法',
				link: 'https://wuliqun.cn/',
				// feed: 'https://wuliqun.cn/atom.xml',
				icon: 'https://wuliqun.cn/star.png',
				avatar: 'https://wuliqun.cn/star.png',
				archs: ['Vue'],
				date: '2026-07-06',
			},
			{
				author: 'MineAPK',
				title: 'MineAPK',
				desc: '目前是一个我的世界版本库',
				link: 'https://mcae.cn/',
				// feed: 'https://mcae.cn/atom.xml',
				icon: 'https://mcae.cn/uploads/MineAPKlogo.png',
				avatar: 'https://mcae.cn/uploads/MineAPKlogo.png',
				archs: ['HTML', 'EdgeOne'],
				date: '2026-07-09',
			},
			{
				author: '笔尖代码',
				title: '笔尖代码',
				desc: '笔尖代码 - 一份汇聚前端、后端、数据库、运维、系统知识的个人技术文档库',
				link: 'https://123456l.com/',
				// feed: 'https://123456l.com/atom.xml',
				icon: 'https://123456l.com/assets/images/logo.png',
				avatar: 'https://123456l.com/assets/images/logo.png',
				archs: ['PHP', 'EdgeOne'],
				date: '2026-07-12',
			},
			{
				author: 'Zorro',
				title: 'Zorro‘s Blog',
				desc: '记录生活、分享技术',
				link: 'https://blog.zuodev.top/',
				feed: 'https://blog.zuodev.top/atom.xml',
				icon: 'https://blog.zuodev.top/file/picture/UserPicture.png',
				avatar: 'https://blog.zuodev.top/file/picture/UserPicture.png',
				archs: ['Vue', 'Cloudflare'],
				date: '2026-07-14',
			},
			{
				author: 'Aimerting',
				title: 'Aimerting',
				desc: '「纯粹祈愿皆成真」',
				link: 'https://blog.xuioo.com/',
				feed: 'https://blog.xuioo.com/atom.xml',
				icon: 'https://blog.xuioo.com/avatar.jpg',
				avatar: 'https://blog.xuioo.com/avatar.jpg',
				archs: ['Astro', 'EdgeOne'],
				date: '2026-07-20',
			},
			{
				author: 'xane',
				title: 'xane',
				desc: 'Keep going.',
				link: 'https://xane.eu.cc',
				feed: 'https://xane.eu.cc/rss.xml',
				icon: 'https://xane.eu.cc/assets/images/avatar.webp',
				avatar: 'https://xane.eu.cc/assets/images/avatar.webp',
				archs: ['Astro', 'Cloudflare'],
				date: '2026-07-21',
			},
			{
				author: 'Zero',
				title: 'Zero - 浮生',
				desc: '浮生一刹万般皆舍.',
				link: 'https://vtdd.vip',
				feed: 'https://vtdd.vip/rss.xml',
				icon: 'https://vtdd.vip/_astro/avatar.ryzKiMN3_19g6Gw.webp',
				avatar: 'https://vtdd.vip/_astro/avatar.ryzKiMN3_19g6Gw.webp',
				archs: ['Astro', 'EdgeOne'],
				date: '2026-07-21',
			},
			{
				author: '萧小晓',
				title: '萧小晓',
				desc: '一个爱写文的菜鸡。',
				link: 'https://blog.lxlovo.top',
				feed: 'https://blog.lxlovo.top/rss.xml',
				icon: 'https://www.lxlovo.top/png.png',
				avatar: 'https://www.lxlovo.top/png.png',
				archs: ['Astro', 'Cloudflare'],
				date: '2026-07-21',
			},
			{
				author: '极客指北',
				title: '极客指北',
				desc: '探索科技之路，分享美好生活！',
				link: 'https://www.90svip.cn',
				feed: 'https://www.90svip.cn/wp-sitemap.xml',
				icon: 'https://www.90svip.cn/logo.png',
				avatar: 'https://www.90svip.cn/logo.png',
				archs: ['PHP', 'EdgeOne'],
				date: '2026-07-21',
			},
			{
				author: '年华',
				title: '年华',
				desc: '分享生活和技术。',
				link: 'https://blog.amamo.top',
				feed: 'https://blog.amamo.top/rss.xml',
				icon: 'https://q1.qlogo.cn/g?b=qq&nk=1323860289&s=640',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=1323860289&s=640',
				archs: ['Astro', 'Vercel'],
				date: '2026-07-21',
			},
			{
				author: 'Xixmu',
				title: 'Xixmu',
				desc: '在记忆干枯前描绘。',
				link: 'https://xixmu.top',
				feed: 'https://xixmu.top/rss.xml',
				icon: 'https://xixmu.top/_astro/head_ima.rsW3s28l_1KtIxl.avif',
				avatar: 'https://xixmu.top/_astro/head_ima.rsW3s28l_1KtIxl.avif',
				archs: ['Astro', 'EdgeOne'],
				date: '2026-08-04',
			},
			{
				author: '星诺',
				title: '星诺的博客',
				desc: '只要热爱，太阳就会升起！',
				link: 'https://blog.astrvow.com/',
				feed: 'https://blog.astrvow.com/atom.xml',
				icon: 'https://blog.astrvow.com/_astro/logo.DuHgmi9I_1k5uPc.webp',
				avatar: 'https://blog.astrvow.com/_astro/logo.DuHgmi9I_1k5uPc.webp',
				archs: ['Astro', 'Cloudflare'],
				date: '2026-08-04',
			},

			{
				author: 'Sky',
				title: 'SkyのXnok',
				desc: '记录学习、生活与思考',
				link: 'https://201562.xyz/',
				feed: 'https://201562.xyz/rss.xml',
				icon: 'https://201562.xyz/avatar.png',
				avatar: 'https://201562.xyz/avatar.png',
				archs: ['Astro', 'Cloudflare'],
				date: '2026-08-10',
			},
			{
				author: 'Silvaire',
				title: 'Silvaire\'s Blog',
				desc: 'A student who is learning frontend development',
				link: 'https://silvaire.top/',
				feed: 'https://silvaire.top/feed.xml',
				icon: 'https://wsrv.nl/?url=avatars.githubusercontent.com/u/184231508?s=400&u=0a370792ba6bbb95a04d309171b562bcd7283a0f&v=3',
				avatar: 'https://wsrv.nl/?url=avatars.githubusercontent.com/u/184231508?s=400&u=0a370792ba6bbb95a04d309171b562bcd7283a0f&v=3',
				archs: ['Vue', 'Vercel'],
				date: '2026-08-12',
			},
			{
				author: '临渊羡鱼',
				title: '临渊羡鱼',
				desc: '久有羡鱼意，不甘空望川. 躬身耕岁月，步步赴清澜',
				link: 'https://x1anyu.cn',
				feed: 'https://x1anyu.cn/rss.xml',
				icon: 'https://x1anyu.cn/assets/images/avatar.png',
				avatar: 'https://x1anyu.cn/assets/images/avatar.png',
				archs: ['Astro', 'EdgeOne'],
				date: '2026-08-19',
			},
			{
				author: '左沐',
				title: '左沐の手册',
				desc: '热爱是拯救无趣人生的唯一途径',
				link: 'https://azuma.mstzuomu.space',
				feed: 'https://azuma.mstzuomu.space/rss.xml',
				icon: 'https://tu.mstzuomu.space/file/头像/1786942479049_azumahead.jpg',
				avatar: 'https://tu.mstzuomu.space/file/头像/1786942479049_azumahead.jpg',
				archs: ['Astro', 'Cloudflare'],
				date: '2026-08-20',
			},
			{
				author: 'Lin',
				title: 'Lin Blog',
				desc: '记录技术、互联网与日常观察',
				link: 'https://linlog.top',
				// feed: 'https://linlog.top/rss.xml',
				icon: 'https://linlog.top/api/uploads/2026/09/1788411216332767920-dca59196a965c5e8.jpg',
				avatar: 'https://linlog.top/api/uploads/2026/09/1788411216332767920-dca59196a965c5e8.jpg',
				archs: ['Cloudflare'],
				date: '2026-09-03',
			},
			// {
			// 	author: 'isYangs',
			// 	desc: '一个前端Bug构造师的博客',
			// 	link: 'https://www.isyangs.cn/',
			// 	feed: 'https://www.isyangs.cn/feed.xml',
			// 	icon: 'https://www.isyangs.cn/favicon.svg',
			// 	avatar: 'https://7.isyangs.cn/8/655c9835780a0-8.jpg',
			// 	archs: ['Vue', '国内 CDN'],
			// 	date: '2024-01-29',
			// 	comment: '高中时认识的小学校友，目前从事前端开发。',
			// },
		],
	},
	// #endregion
] satisfies FeedGroup[]
